#!/usr/bin/env python
"""
Author: petteri gmail com
have fun
"""
import apt_pkg
import sys


def usage(pname):
    print "Compare debian package version numbers"
    print "Usage: [-m] %s version version" % pname
    print "  -m\t output suitable for machine/script usage (strcmp style)"
    print "Example: %s 1.2-1 1.2+lenny1" % pname
    sys.exit(2)


def main():
    pname = sys.argv[0].split("/")[-1]
    machine = False

    if len(sys.argv) == 4:
        if sys.argv[1] == "-m":
            sys.argv.pop(1)
            machine = True
        else:
            usage(pname)

    if len(sys.argv) != 3:
        usage(pname)

    apt_pkg.InitSystem()
    ret = apt_pkg.VersionCompare(sys.argv[1], sys.argv[2])

    if machine:
        print ret
    else:
        if ret > 0:
            print "%s > %s" % (sys.argv[1], sys.argv[2])
        elif ret < 0:
            print "%s < %s" % (sys.argv[1], sys.argv[2])
        else:
            print "%s = %s" % (sys.argv[1], sys.argv[2])


if __name__ =='__main__':
    main()


